function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Factorial_ForLoop"};
	this.sidHashMap["Factorial_ForLoop"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Factorial_ForLoop:2"};
	this.sidHashMap["Factorial_ForLoop:2"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "Factorial_ForLoop:6"};
	this.sidHashMap["Factorial_ForLoop:6"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/in1"] = {sid: "Factorial_ForLoop:10"};
	this.sidHashMap["Factorial_ForLoop:10"] = {rtwname: "<Root>/in1"};
	this.rtwnameHashMap["<Root>/Constant"] = {sid: "Factorial_ForLoop:11"};
	this.sidHashMap["Factorial_ForLoop:11"] = {rtwname: "<Root>/Constant"};
	this.rtwnameHashMap["<Root>/Display"] = {sid: "Factorial_ForLoop:7"};
	this.sidHashMap["Factorial_ForLoop:7"] = {rtwname: "<Root>/Display"};
	this.rtwnameHashMap["<Root>/For Iterator Subsystem"] = {sid: "Factorial_ForLoop:2"};
	this.sidHashMap["Factorial_ForLoop:2"] = {rtwname: "<Root>/For Iterator Subsystem"};
	this.rtwnameHashMap["<Root>/MATLAB Function"] = {sid: "Factorial_ForLoop:6"};
	this.sidHashMap["Factorial_ForLoop:6"] = {rtwname: "<Root>/MATLAB Function"};
	this.rtwnameHashMap["<Root>/Scope"] = {sid: "Factorial_ForLoop:8"};
	this.sidHashMap["Factorial_ForLoop:8"] = {rtwname: "<Root>/Scope"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "Factorial_ForLoop:15"};
	this.sidHashMap["Factorial_ForLoop:15"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<S1>/Arr1"] = {sid: "Factorial_ForLoop:3"};
	this.sidHashMap["Factorial_ForLoop:3"] = {rtwname: "<S1>/Arr1"};
	this.rtwnameHashMap["<S1>/For Iterator"] = {sid: "Factorial_ForLoop:4"};
	this.sidHashMap["Factorial_ForLoop:4"] = {rtwname: "<S1>/For Iterator"};
	this.rtwnameHashMap["<S1>/Product"] = {sid: "Factorial_ForLoop:13"};
	this.sidHashMap["Factorial_ForLoop:13"] = {rtwname: "<S1>/Product"};
	this.rtwnameHashMap["<S1>/Unit Delay"] = {sid: "Factorial_ForLoop:14"};
	this.sidHashMap["Factorial_ForLoop:14"] = {rtwname: "<S1>/Unit Delay"};
	this.rtwnameHashMap["<S1>/u"] = {sid: "Factorial_ForLoop:5"};
	this.sidHashMap["Factorial_ForLoop:5"] = {rtwname: "<S1>/u"};
	this.rtwnameHashMap["<S2>:1"] = {sid: "Factorial_ForLoop:6:1"};
	this.sidHashMap["Factorial_ForLoop:6:1"] = {rtwname: "<S2>:1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
